esphome:
  name: victron-test
  friendly_name: Victron BLE Test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Over-The-Air updates
ota:
  - platform: esphome
    password: "VictronTest2025"

# WiFi configuration - REPLACE THESE VALUES
wifi:
  ssid: "Rocket"
  password: "Ed1nburgh2015!"
  
  # Enable fallback hotspot if WiFi fails
  ap:
    ssid: "Victron-Test"
    password: "12345678"

captive_portal:

# Enable Bluetooth
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# Victron BLE devices
victron_ble:
  - mac_address: c0:3b:98:39:e6:fe
    bindkey: "8e85273557314e1eb83a94843d7c6265"
    id: shunt_device
  - mac_address: e8:86:01:5d:79:38
    bindkey: "d04652f10b4c5ad5066e34e332af6919"
    id: solar_device

# Basic sensors
sensor:
  - platform: victron_ble
    victron_ble_id: shunt_device
    battery_voltage:
      name: "Battery Voltage"
      id: battery_voltage

  - platform: victron_ble
    victron_ble_id: solar_device
    charger_voltage:
      name: "Solar Voltage"
      id: solar_voltage

# Simple logging every 30 seconds
interval:
  - interval: 30s
    then:
      - logger.log:
          format: "Battery: %.2fV | Solar: %.2fV"
          args: ['id(battery_voltage).state', 'id(solar_voltage).state']
          level: INFO

# Web server for monitoring
web_server:
  port: 80