esphome:
  name: victron-simple
  friendly_name: Victron BLE Simple

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Over-The-Air updates
ota:
  - platform: esphome
    password: "VictronTest2025"

# WiFi configuration
wifi:
  ssid: "Rocket"
  password: "Ed1nburgh2015!"
  
  # Enable fallback hotspot if WiFi fails
  ap:
    ssid: "Victron-Simple"
    password: "12345678"

captive_portal:

# Enable Bluetooth
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    - mac_address: c0:3b:98:39:e6:fe
      then:
        - logger.log: "Found SHUNT device!"
    - mac_address: e8:86:01:5d:79:38
      then:
        - logger.log: "Found SOLAR device!"

# Web server for monitoring
web_server:
  port: 80

# Status LED
status_led:
  pin:
    number: GPIO2
    inverted: true

# Simple status
text_sensor:
  - platform: template
    name: "System Status"
    id: system_status
    update_interval: 30s
    lambda: |-
      return {"System Running"};

# Uptime sensor
sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s